CREATE TABLE IF NOT EXISTS seven_sms
(
    id       INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    config   LONGTEXT NOT NULL,
    response LONGTEXT  DEFAULT NULL,
    created  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
